INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Microsoft', 'MSFT', 'USA', 3049.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Apple', 'AAPL', 'USA', 2818.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Saudi Aramco', '2222.SR', 'SAU', 2065.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('NVIDIA', 'NVDA', 'USA', 1970.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Amazon', 'AMZN', 'USA', 1817.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Alphabet (Google)', 'GOOG', 'USA', 1798.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Meta Platforms (Facebook)', 'META', 'USA', 1233.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Berkshire Hathaway', 'BRK-B', 'USA', 905.29);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Eli Lilly', 'LLY', 'USA', 731.18);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TSMC', 'TSM', 'TWN', 671.79);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Tesla', 'TSLA', 'USA', 611.38);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Broadcom', 'AVGO', 'USA', 606.88);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Visa', 'V', 'USA', 582.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Novo Nordisk', 'NVO', 'DNK', 550.96);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('JPMorgan Chase', 'JPM', 'USA', 529.95);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('UnitedHealth', 'UNH', 'USA', 487.65);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Walmart', 'WMT', 'USA', 472.64);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('LVMH', 'MC.PA', 'FRA', 459.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mastercard', 'MA', 'USA', 441.64);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Exxon Mobil', 'XOM', 'USA', 412.34);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Johnson & Johnson', 'JNJ', 'USA', 389.83);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Procter & Gamble', 'PG', 'USA', 378.9);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Home Depot', 'HD', 'USA', 370.19);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ASML', 'ASML', 'NLD', 368.25);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Samsung', '005930.KS', 'KOR', 366.06);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Tencent', 'TCEHY', 'CHN', 351.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Merck', 'MRK', 'USA', 328.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Costco', 'COST', 'USA', 327.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Toyota', 'TM', 'JPN', 316.87);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AbbVie', 'ABBV', 'USA', 314.59);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Oracle', 'ORCL', 'USA', 307.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kweichow Moutai', '600519.SS', 'CHN', 299.28);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nestlé', 'NESN.SW', 'CHE', 288.7);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Chevron', 'CVX', 'USA', 286.27);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AMD', 'AMD', 'USA', 285.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Salesforce', 'CRM', 'USA', 283.43);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank of America', 'BAC', 'USA', 267.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Coca-Cola', 'KO', 'USA', 263.92);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hermès', 'RMS.PA', 'FRA', 260.88);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('L''Oréal', 'OR.PA', 'FRA', 260.61);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Netflix', 'NFLX', 'USA', 252.54);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ICBC', '1398.HK', 'CHN', 251.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Adobe', 'ADBE', 'USA', 250.15);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Reliance Industries', 'RELIANCE.NS', 'IND', 243.99);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('International Holding Company', 'IHC.AE', 'ARE', 238.59);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Accenture', 'ACN', 'IRL', 236.57);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Pepsico', 'PEP', 'USA', 233.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('PetroChina', '601857.SS', 'CHN', 221.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Thermo Fisher Scientific', 'TMO', 'USA', 218.18);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Linde', 'LIN', 'GBR', 217.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('SAP', 'SAP', 'DEU', 215.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('McDonald', 'MCD', 'USA', 215.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Novartis', 'NVS', 'CHE', 212.77);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Roche', 'ROG.SW', 'CHE', 212.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Abbott Laboratories', 'ABT', 'USA', 207.28);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Shell', 'SHEL', 'GBR', 206.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AstraZeneca', 'AZN', 'GBR', 204.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Agricultural Bank of China', '601288.SS', 'CHN', 202.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cisco', 'CSCO', 'USA', 197.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Walt Disney', 'DIS', 'USA', 197.62);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('T-Mobile US', 'TMUS', 'USA', 195.05);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Wells Fargo', 'WFC', 'USA', 192.68);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Alibaba', 'BABA', 'CHN', 191.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('China Mobile', '0941.HK', 'CHN', 190.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Danaher', 'DHR', 'USA', 187.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Intuit', 'INTU', 'USA', 184.7);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Intel', 'INTC', 'USA', 181.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Tata Consultancy Services', 'TCS.NS', 'IND', 176.98);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('QUALCOMM', 'QCOM', 'USA', 172.87);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Verizon', 'VZ', 'USA', 170.94);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Pinduoduo', 'PDD', 'CHN', 169.64);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('IBM', 'IBM', 'USA', 169.58);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank of China', '601988.SS', 'CHN', 168.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('General Electric', 'GE', 'USA', 166.87);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Comcast', 'CMCSA', 'USA', 166.42);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Applied Materials', 'AMAT', 'USA', 164.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('China Construction Bank', '601939.SS', 'CHN', 162.57);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Uber', 'UBER', 'USA', 162.38);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Caterpillar', 'CAT', 'USA', 161.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nike', 'NKE', 'USA', 160.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ServiceNow', 'NOW', 'USA', 158.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Pfizer', 'PFE', 'USA', 156.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Union Pacific Corporation', 'UNP', 'USA', 156.65);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('American Express', 'AXP', 'USA', 155.31);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Dior', 'CDI.PA', 'FRA', 155.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Amgen', 'AMGN', 'USA', 154.97);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TotalEnergies', 'TTE', 'FRA', 150.62);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Siemens', 'SIE.DE', 'DEU', 149.91);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Texas Instruments', 'TXN', 'USA', 148.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BHP Group', 'BHP', 'AUS', 147.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('HSBC', 'HSBC', 'GBR', 145.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Philip Morris', 'PM', 'USA', 142.14);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Morgan Stanley', 'MS', 'USA', 142.05);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Inditex', 'IDEXY', 'ESP', 138.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Royal Bank Of Canada', 'RY', 'CAN', 138.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('S&P Global', 'SPGI', 'USA', 137.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Intuitive Surgical', 'ISRG', 'USA', 137.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Arm Holdings', 'ARM', 'GBR', 137.08);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('HDFC Bank', 'HDB', 'IND', 136.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Stryker Corporation', 'SYK', 'USA', 135.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Prosus', 'PRX.AS', 'NLD', 134.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Lowe''s Companies', 'LOW', 'USA', 133.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ConocoPhillips', 'COP', 'USA', 131.18);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Honeywell', 'HON', 'USA', 130.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Goldman Sachs', 'GS', 'USA', 127.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Schneider Electric', 'SU.PA', 'FRA', 126.8);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('United Parcel Service', 'UPS', 'USA', 126.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Unilever', 'UL', 'GBR', 126.67);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Airbus', 'AIR.PA', 'NLD', 126.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Commonwealth Bank', 'CBA.AX', 'AUS', 126.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Anheuser-Busch Inbev', 'BUD', 'BEL', 125.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Prologis', 'PLD', 'USA', 123.2);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Boeing', 'BA', 'USA', 122.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Booking Holdings (Booking.com)', 'BKNG', 'USA', 122.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sanofi', 'SNY', 'FRA', 121.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Lam Research', 'LRCX', 'USA', 121.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BlackRock', 'BLK', 'USA', 120.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AT&T', 'T', 'USA', 120.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Elevance Health', 'ELV', 'USA', 119.61);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Raytheon Technologies', 'RTX', 'USA', 119.42);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Deutsche Telekom', 'DTE.DE', 'DEU', 119.13);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mitsubishi UFJ Financial', 'MUFG', 'JPN', 118.63);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Charles Schwab', 'SCHW', 'USA', 117.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nextera Energy', 'NEE', 'USA', 116.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Medtronic', 'MDT', 'IRL', 113.91);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Eaton', 'ETN', 'IRL', 113.77);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TJX Company', 'TJX', 'USA', 113.26);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CM Bank', '3968.HK', 'CHN', 113.16);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Petrobras', 'PBR', 'BRA', 112.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Tokyo Electron', '8035.T', 'JPN', 112.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Keyence', '6861.T', 'JPN', 112.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Progressive', 'PGR', 'USA', 112.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Vertex Pharmaceuticals', 'VRTX', 'USA', 111.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sony', 'SONY', 'JPN', 108.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Toronto Dominion Bank', 'TD', 'CAN', 108.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Starbucks', 'SBUX', 'USA', 108.26);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Regeneron Pharmaceuticals', 'REGN', 'USA', 107.69);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Air Liquide', 'AI.PA', 'FRA', 107.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Rio Tinto', 'RIO', 'GBR', 107.05);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Citigroup', 'C', 'USA', 106.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Automatic Data Processing', 'ADP', 'USA', 105.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('China Shenhua Energy', '601088.SS', 'CHN', 104.97);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Allianz', 'ALV.DE', 'DEU', 104.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bristol-Myers Squibb', 'BMY', 'USA', 104.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Chubb', 'CB', 'CHE', 104.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Lockheed Martin', 'LMT', 'USA', 104.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CNOOC', '0883.HK', 'CHN', 103.6);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Deere & Company', 'DE', 'USA', 102.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('NTT (Nippon Telegraph & Telephone)', 'NPPXF', 'JPN', 101.92);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ping An Insurance', '601318.SS', 'CHN', 101.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('China Life Insurance', '601628.SS', 'CHN', 101.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cigna', 'CI', 'USA', 100.69);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BP', 'BP', 'GBR', 100.61);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Marsh & McLennan Companies', 'MMC', 'USA', 100.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mondelez', 'MDLZ', 'USA', 99.61);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Boston Scientific', 'BSX', 'USA', 98.29);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Shopify', 'SHOP', 'CAN', 98.13);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CATL', '300750.SZ', 'CHN', 98.13);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sinopec', '600028.SS', 'CHN', 98.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Airbnb', 'ABNB', 'USA', 97.37);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CVS Health', 'CVS', 'USA', 97.15);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Al Rajhi Bank', '1120.SR', 'SAU', 96.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TAQA', 'TAQA.AE', 'ARE', 96.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('EssilorLuxottica', 'EL.PA', 'FRA', 95.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Micron Technology', 'MU', 'USA', 94.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Analog Devices', 'ADI', 'USA', 94.27);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AIA', '1299.HK', 'HKG', 93.54);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Compagnie Financière Richemont', 'CFR.SW', 'CHE', 91.77);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Gilead Sciences', 'GILD', 'USA', 91.64);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Palo Alto Networks', 'PANW', 'USA', 91.14);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Fiserv', 'FI', 'USA', 90.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CSL', 'CSL.AX', 'AUS', 90.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('KLA', 'KLAC', 'USA', 90.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Blackstone Group', 'BX', 'USA', 90.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Zoetis', 'ZTS', 'USA', 90.29);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('UBS', 'UBS', 'CHE', 90.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ICICI Bank', 'IBN', 'IND', 89.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mitsubishi Corporation', '8058.T', 'JPN', 89.23);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('American Tower', 'AMT', 'USA', 88.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Fast Retailing', '9983.T', 'JPN', 88.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Synopsys', 'SNPS', 'USA', 87.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('China Yangtze Power', '600900.SS', 'CHN', 87.36);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Safran', 'SAF.PA', 'FRA', 86.23);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('SoftBank', '9984.T', 'JPN', 85.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('GlaxoSmithKline', 'GSK', 'GBR', 85.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('KKR & Co.', 'KKR', 'USA', 85.15);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Diageo', 'DEO', 'GBR', 85.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Canadian National Railway', 'CNI', 'CAN', 84.57);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ABB', 'ABBN.SW', 'CHE', 84.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Infosys', 'INFY', 'IND', 83.75);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Arista Networks', 'ANET', 'USA', 83.67);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Shin-Etsu Chemical', '4063.T', 'JPN', 83.67);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('RELX', 'RELX', 'GBR', 83.67);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Waste Management', 'WM', 'USA', 83.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('SK Hynix', '000660.KS', 'KOR', 83.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Equinix', 'EQIX', 'USA', 83.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('HCA Healthcare', 'HCA', 'USA', 83.41);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mercedes-Benz', 'MBG.DE', 'DEU', 83.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cadence Design Systems', 'CDNS', 'USA', 82.63);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('MercadoLibre', 'MELI', 'ARG', 82.6);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sherwin-Williams', 'SHW', 'USA', 81.94);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('State Bank of India', 'SBIN.NS', 'IND', 81.77);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Porsche', 'P911.DE', 'DEU', 81.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Life Insurance Corporation of India (LIC)', 'LICI.NS', 'IND', 81.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Atlas Copco', 'ATCO-B.ST', 'SWE', 81.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Canadian Pacific Railway', 'CP', 'CAN', 80.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Workday', 'WDAY', 'USA', 80.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bharti Airtel', 'BHARTIARTL.NS', 'IND', 80.15);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Stellantis', 'STLA', 'NLD', 80.14);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hitachi', '6501.T', 'JPN', 79.36);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Intercontinental Exchange', 'ICE', 'USA', 79.23);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AXA', 'CS.PA', 'FRA', 78.75);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CME Group', 'CME', 'USA', 78.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Illinois Tool Works', 'ITW', 'USA', 77.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank Central Asia', 'BBCA.JK', 'IDN', 77.69);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Zurich Insurance Group', 'ZURN.SW', 'CHE', 76.95);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Wuliangye Yibin', '000858.SZ', 'CHN', 76.45);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BMW', 'BMW.DE', 'DEU', 76.15);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Investor AB', 'INVE-B.ST', 'SWE', 76.14);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Snowflake', 'SNOW', 'USA', 75.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CSX Corporation', 'CSX', 'USA', 75.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('General Dynamics', 'GD', 'USA', 75.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ferrari', 'RACE', 'ITA', 74.98);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Merck KGaA', 'MRK.DE', 'DEU', 74.83);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CrowdStrike', 'CRWD', 'USA', 74.8);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Equinor', 'EQNR', 'NOR', 74.22);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Enbridge', 'ENB', 'CAN', 74.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Southern Company', 'SO', 'USA', 73.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Marriott International', 'MAR', 'USA', 72.79);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('China Telecom', '0728.HK', 'CHN', 72.71);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Chipotle Mexican Grill', 'CMG', 'USA', 72.57);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Volkswagen', 'VOW3.DE', 'DEU', 72.54);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Altria Group', 'MO', 'USA', 72.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Vinci', 'DG.PA', 'FRA', 72.14);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BYD', '002594.SZ', 'CHN', 72.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Iberdrola', 'IBE.MC', 'ESP', 71.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Thomson Reuters', 'TRI', 'CAN', 71.75);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Duke Energy', 'DUK', 'USA', 71.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sumitomo Mitsui Financial Group', 'SMFG', 'JPN', 71.25);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Becton Dickinson', 'BDX', 'USA', 71.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Canadian Natural Resources', 'CNQ', 'CAN', 71.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Colgate-Palmolive', 'CL', 'USA', 70.99);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Walmex', 'WMMVF', 'MEX', 70.96);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('LG Energy Solution', '373220.KS', 'KOR', 70.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Moody''s', 'MCO', 'USA', 70.16);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('NetEase', 'NTES', 'CHN', 70.07);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BNP Paribas', 'BNP.PA', 'FRA', 70.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Target', 'TGT', 'USA', 69.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Schlumberger', 'SLB', 'USA', 69.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('National Australia Bank', 'NAB.AX', 'AUS', 69.35);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Northrop Grumman', 'NOC', 'USA', 69.18);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank of Montreal', 'BMO', 'CAN', 68.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('British American Tobacco', 'BTI', 'GBR', 68.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Parker-Hannifin', 'PH', 'USA', 68.19);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hindustan Unilever', 'HINDUNILVR.NS', 'IND', 67.91);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('McKesson', 'MCK', 'USA', 67.83);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('The Saudi National Bank', '1180.SR', 'SAU', 67.63);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Itaú Unibanco', 'ITUB', 'BRA', 66.97);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TransDigm', 'TDG', 'USA', 66.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Siemens Healthineers', 'SHL.DE', 'DEU', 65.97);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Postal Savings Bank of China', '601658.SS', 'CHN', 65.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Santander', 'SAN', 'ESP', 65.65);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Enel', 'ENEL.MI', 'ITA', 65.5);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ADNOC Gas', 'ADNOCGAS.AE', 'ARE', 65.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nintendo', '7974.T', 'JPN', 65.37);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('EOG Resources', 'EOG', 'USA', 65.23);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('DBS Group', 'D05.SI', 'SGP', 65.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Meituan', '3690.HK', 'CHN', 64.94);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sberbank', 'SBER.ME', 'RUS', 64.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mitsui Bussan', '8031.T', 'JPN', 64.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Brookfield Corporation', 'BN', 'CAN', 64.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Amphenol', 'APH', 'USA', 64.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('U.S. Bancorp', 'USB', 'USA', 64.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nongfu Spring', '9633.HK', 'CHN', 64.25);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cintas', 'CTAS', 'USA', 64.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Itōchū Shōji', '8001.T', 'JPN', 64.08);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Trane Technologies', 'TT', 'IRL', 63.99);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('KDDI', '9433.T', 'JPN', 63.94);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Dell', 'DELL', 'USA', 63.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('SABIC', '2010.SR', 'SAU', 63.54);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Southern Copper', 'SCCO', 'USA', 63.41);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('PayPal', 'PYPL', 'USA', 63.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ecolab', 'ECL', 'USA', 63.39);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Apollo Global Management', 'APO', 'USA', 63.36);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Phillips 66', 'PSX', 'USA', 62.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Rosneft', 'ROSN.ME', 'RUS', 62.83);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Daiichi Sankyō', '4568.T', 'JPN', 62.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Aon', 'AON', 'GBR', 62.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('O''Reilly Automotive', 'ORLY', 'USA', 62.5);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Munich RE (Münchener Rück)', 'MUV2.DE', 'DEU', 62.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Marathon Petroleum', 'MPC', 'USA', 62.39);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ITC', 'ITC.NS', 'IND', 61.98);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Chugai Pharmaceutical', '4519.T', 'JPN', 61.77);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Dassault Systèmes', 'DSY.PA', 'FRA', 61.58);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('NXP Semiconductors', 'NXPI', 'NLD', 61.56);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Alimentation Couche-Tard', 'ATD.TO', 'CAN', 61.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Recruit', '6098.T', 'JPN', 61.06);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('FedEx', 'FDX', 'USA', 60.83);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('London Stock Exchange', 'LSEG.L', 'GBR', 60.61);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Emerson', 'EMR', 'USA', 60.54);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Enterprise Products', 'EPD', 'USA', 60.11);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('America Movil', 'AMX', 'MEX', 59.89);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Banco Bilbao Vizcaya Argentaria', 'BBVA', 'ESP', 59.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Westpac Banking', 'WBC.AX', 'AUS', 59.67);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Roper Technologies', 'ROP', 'USA', 59.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank Rakyat Indonesia', 'BBRI.JK', 'IDN', 59.24);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Glencore', 'GLCNF', 'CHE', 59.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Constellation Software', 'CSU.TO', 'CAN', 58.88);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank of Communications', '601328.SS', 'CHN', 58.8);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Oriental Land', '4661.T', 'JPN', 58.47);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Marvell Technology Group', 'MRVL', 'USA', 58.42);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Norfolk Southern', 'NSC', 'USA', 58.27);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Republic Services', 'RSG', 'USA', 58.2);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Honda', 'HMC', 'JPN', 58.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('PNC Financial Services', 'PNC', 'USA', 58.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Intesa Sanpaolo', 'ISP.MI', 'ITA', 58.08);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Paccar', 'PCAR', 'USA', 58.03);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('lululemon athletica', 'LULU', 'CAN', 57.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Scotiabank', 'BNS', 'CAN', 57.77);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Vale', 'VALE', 'BRA', 57.7);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Midea', '000333.SZ', 'CHN', 57.68);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Monster Beverage', 'MNST', 'USA', 57.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Fortescue', 'FMG.AX', 'AUS', 57.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Tokio Marine', '8766.T', 'JPN', 56.5);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kering', 'KER.PA', 'FRA', 56.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Simon Property Group', 'SPG', 'USA', 56.35);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Larsen & Toubro', 'LT.NS', 'IND', 56.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('DHL Group (Deutsche Post)', 'DHL.DE', 'DEU', 56.05);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cement Roadstone Holding', 'CRH', 'IRL', 55.97);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('UniCredit', 'UCG.MI', 'ITA', 55.96);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Freeport-McMoRan', 'FCX', 'USA', 55.88);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Saudi Telecom Company', '7010.SR', 'SAU', 55.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ANZ Bank', 'ANZ.AX', 'AUS', 55.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('MediaTek', '2454.TW', 'TWN', 55.44);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Autodesk', 'ADSK', 'USA', 55.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Motorola Solutions', 'MSI', 'USA', 54.86);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('HCL Technologies', 'HCLTECH.NS', 'IND', 54.45);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Heineken', 'HEIA.AS', 'NLD', 54.36);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Volvo Group', 'VOLVF', 'SWE', 54.32);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Pioneer Natural Resources', 'PXD', 'USA', 54.31);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Denso', '6902.T', 'JPN', 53.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Estee Lauder', 'EL', 'USA', 53.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Welltower', 'WELL', 'USA', 53.13);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Arthur J. Gallagher & Co.', 'AJG', 'USA', 53.11);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Universal Music Group', 'UMG.AS', 'NLD', 53.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Atlassian', 'TEAM', 'AUS', 53.03);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Occidental Petroleum', 'OXY', 'USA', 52.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Edwards Lifesciences', 'EW', 'USA', 52.75);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Reckitt Benckiser', 'RKT.L', 'GBR', 52.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Fortinet', 'FTNT', 'USA', 51.94);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Air Products and Chemicals', 'APD', 'USA', 51.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hilton Worldwide', 'HLT', 'USA', 51.57);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Capital One', 'COF', 'USA', 51.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Lukoil', 'LKOH.ME', 'RUS', 51.29);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('3M', 'MMM', 'USA', 51.16);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Palantir', 'PLTR', 'USA', 50.82);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('The Travelers Companies', 'TRV', 'USA', 50.62);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Spotify', 'SPOT', 'SWE', 50.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Public Storage', 'PSA', 'USA', 50.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Foxconn Industrial Internet', '601138.SS', 'CHN', 50.16);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Energy Transfer Partners', 'ET', 'USA', 50.14);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('MetLife', 'MET', 'USA', 50.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bajaj Finance', 'BAJFINANCE.NS', 'IND', 50.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ACWA POWER Company', '2082.SR', 'SAU', 49.85);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ross Stores', 'ROST', 'USA', 49.83);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ENI', 'E', 'ITA', 49.59);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('National Grid', 'NGG', 'GBR', 49.57);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Maaden', '1211.SR', 'SAU', 49.54);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Copart', 'CPRT', 'USA', 49.33);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Adyen', 'ADYEN.AS', 'NLD', 49.3);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('DoorDash', 'DASH', 'USA', 49.19);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mindray', '300760.SZ', 'CHN', 48.9);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Macquarie', 'MQG.AX', 'AUS', 48.82);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Carrier', 'CARR', 'USA', 48.69);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Industrial Bank', '601166.SS', 'CHN', 48.68);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nu Holdings', 'NU', 'BRA', 48.59);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('American International Group', 'AIG', 'USA', 48.56);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('D. R. Horton', 'DHI', 'USA', 48.47);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Zijin Mining', '601899.SS', 'CHN', 48.47);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Block', 'SQ', 'USA', 48.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Wesfarmers', 'WES.AX', 'AUS', 48.41);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ford', 'F', 'USA', 48.23);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Valero Energy', 'VLO', 'USA', 48.2);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Supermicro', 'SMCI', 'USA', 48.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Old Dominion Freight Line', 'ODFL', 'USA', 48.03);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BAE Systems', 'BA.L', 'GBR', 47.98);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('IDEXX Laboratories', 'IDXX', 'USA', 47.86);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('AutoZone', 'AZO', 'USA', 47.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cencora', 'COR', 'USA', 47.65);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('W. W. Grainger', 'GWW', 'USA', 47.59);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Compass Group', 'CPG.L', 'GBR', 47.17);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Crown Castle', 'CCI', 'USA', 47.13);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sika', 'SIKA.SW', 'CHE', 47.11);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Truist Financial', 'TFC', 'USA', 47.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Mizuho Financial Group', 'MFG', 'JPN', 46.89);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Infineon', 'IFX.DE', 'DEU', 46.71);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nucor', 'NUE', 'USA', 46.7);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Japan Tobacco', '2914.T', 'JPN', 46.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Aflac', 'AFL', 'USA', 46.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Takeda Pharmaceutical', 'TAK', 'JPN', 46.2);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hess', 'HES', 'USA', 45.8);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('General Motors', 'GM', 'USA', 45.75);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Realty Income', 'O', 'USA', 45.58);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('ING', 'ING', 'NLD', 45.37);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sempra Energy', 'SRE', 'USA', 45.29);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sun Pharmaceutical', 'SUNPHARMA.NS', 'IND', 45.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Foxconn (Hon Hai Precision Industry)', '2317.TW', 'TWN', 45.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Constellation Brands', 'STZ', 'USA', 45.19);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Adani Enterprises', 'ADANIENT.NS', 'IND', 45.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('BASF', 'BAS.DE', 'DEU', 45.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('MSCI', 'MSCI', 'USA', 45.0);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Holcim Group', 'HOLN.SW', 'CHE', 44.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('IQVIA', 'IQV', 'USA', 44.87);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Alpha Dhabi', 'ALPHADHABI.AE', 'ARE', 44.87);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hikvision', '002415.SZ', 'CHN', 44.85);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Paychex', 'PAYX', 'USA', 44.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('DexCom', 'DXCM', 'USA', 44.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Microchip Technology', 'MCHP', 'USA', 44.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('OCBC Bank', 'O39.SI', 'SGP', 44.74);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Interactive Brokers', 'IBKR', 'USA', 44.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Pacific Gas and Electric', 'PCG', 'USA', 44.47);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('United Rentals', 'URI', 'USA', 44.22);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TE Connectivity', 'TEL', 'CHE', 44.19);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hoya', '7741.T', 'JPN', 44.08);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Manulife Financial', 'MFC', 'CAN', 43.88);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Waste Connections', 'WCN', 'USA', 43.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Digital Realty', 'DLR', 'USA', 43.84);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hyundai', 'HYMTF', 'KOR', 43.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Humana', 'HUM', 'USA', 43.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Maruti Suzuki India', 'MARUTI.NS', 'IND', 43.78);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kraft Heinz', 'KHC', 'USA', 43.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CIBC', 'CM', 'CAN', 43.72);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Emirates Telecom (Etisalat Group)', 'EAND.AE', 'ARE', 43.71);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Suncor Energy', 'SU', 'CAN', 43.65);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Samsung Biologics', '207940.KS', 'KOR', 43.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Xiaomi', 'XIACF', 'CHN', 43.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Charter Communications', 'CHTR', 'USA', 43.48);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('American Electric Power', 'AEP', 'USA', 43.35);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Lennar', 'LEN', 'USA', 43.18);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Pernod Ricard', 'RI.PA', 'FRA', 43.15);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Centene', 'CNC', 'USA', 42.9);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Novatek', 'NVTK.ME', 'RUS', 42.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Constellation Energy', 'CEG', 'USA', 42.79);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Naqi Water Company', '2282.SR', 'SAU', 42.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Datadog', 'DDOG', 'USA', 42.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Fomento Económico Mexicano', 'FMX', 'MEX', 42.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Williams Companies', 'WMB', 'USA', 42.51);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Oneok', 'OKE', 'USA', 42.5);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Nordea Bank', 'NDA-FI.HE', 'FIN', 42.35);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank of New York Mellon', 'BK', 'USA', 42.24);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Danone', 'BN.PA', 'FRA', 42.22);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Banco Santander Brasil', 'BSBR', 'BRA', 42.22);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Keurig Dr Pepper', 'KDP', 'USA', 42.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bank Mandiri', 'BMRI.JK', 'IDN', 42.2);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ferguson', 'FERG', 'GBR', 42.1);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Allstate', 'ALL', 'USA', 41.86);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Bayan Resources', 'BYAN.JK', 'IDN', 41.66);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CITIC Securities', '600030.SS', 'CHN', 41.6);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('First Abu Dhabi Bank', 'FAB.AE', 'ARE', 41.5);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Daikin', '6367.T', 'JPN', 41.45);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Tata Motors', 'TATAMOTORS.NS', 'IND', 41.4);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kotak Mahindra Bank', 'KOTAKBANK.NS', 'IND', 41.36);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Oil & Natural Gas', 'ONGC.NS', 'IND', 41.35);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Fastenal', 'FAST', 'USA', 41.3);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Las Vegas Sands', 'LVS', 'USA', 41.26);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('TC Energy', 'TRP', 'CAN', 41.25);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ametek', 'AME', 'USA', 41.12);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Crédit Agricole', 'ACA.PA', 'FRA', 41.09);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Hong Kong Exchanges & Clearing', '0388.HK', 'HKG', 41.02);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kaspi.kz Joint Stock Company', 'KKS.F', 'KAZ', 41.01);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kimberly-Clark', 'KMB', 'USA', 40.97);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Axis Bank', 'AXISBANK.BO', 'IND', 40.87);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ameriprise Financial', 'AMP', 'USA', 40.79);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('L3Harris Technologies', 'LHX', 'USA', 40.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Capgemini', 'CAP.PA', 'FRA', 40.75);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ambev', 'ABEV', 'BRA', 40.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('GE HealthCare Technologies', 'GEHC', 'USA', 40.55);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Ares Management', 'ARES', 'USA', 40.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kuwait Finance House', 'KFH.KW', 'KWT', 40.36);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('STMicroelectronics', 'STM', 'CHE', 40.34);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Sysco', 'SYY', 'USA', 40.23);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Coinbase', 'COIN', 'USA', 40.21);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Dominion Energy', 'D', 'USA', 40.04);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Johnson Controls', 'JCI', 'IRL', 39.82);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('The Trade Desk', 'TTD', 'USA', 39.81);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Experian', 'EXPGF', 'IRL', 39.76);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Cognizant Technology Solutions', 'CTSH', 'USA', 39.73);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('MPLX', 'MPLX', 'USA', 39.71);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Givaudan', 'GIVN.SW', 'CHE', 39.69);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Dow', 'DOW', 'USA', 39.6);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Titan Company', 'TITAN.NS', 'IND', 39.56);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('NTPC Limited', 'NTPC.NS', 'IND', 39.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('The Hershey Company', 'HSY', 'USA', 39.53);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('CITIC Bank', '601998.SS', 'CHN', 39.52);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Gazprom', 'GAZP.ME', 'RUS', 39.46);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Alcon', 'ALC', 'CHE', 39.37);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Kühne + Nagel', 'KNIN.SW', 'CHE', 39.08);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Lonza', 'LONN.SW', 'CHE', 39.08);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Baidu', 'BIDU', 'CHN', 38.93);
INSERT INTO Company (Name, Ticker_Symbol, HQ_Location, Market_Cap_In_Billions) VALUES ('Grupo México', 'GMBXF', 'MEX', 38.92);